import JSZip from "jszip";
import type { Block } from "@webforge/shared";
import { renderDocument } from "@webforge/renderer";
import { requireSite } from "./access.service.js";
import { brandKitForSite } from "./brandkit.service.js";
import { pagesForPublish } from "./page.service.js";

/**
 * Code export (no lock-in): render every page to a self-contained static HTML
 * document (CSS is inlined by the renderer) and bundle them into a ZIP. The
 * output is plain HTML/CSS the user can host anywhere.
 */
export async function exportSiteZip(
  siteId: string,
  userId: string,
): Promise<{ buffer: Buffer; filename: string }> {
  const site = await requireSite(siteId, userId);
  const [pages, brandKit] = await Promise.all([
    pagesForPublish(site._id.toString()),
    brandKitForSite(site._id.toString()),
  ]);

  const zip = new JSZip();
  for (const page of pages) {
    const html = renderDocument({
      page: { title: page.title, tree: page.tree as Block },
      site: { name: site.name },
      brandKit,
    });
    const fileSlug = page.isHome ? "index" : page.slug;
    zip.file(`${fileSlug}.html`, html);
  }

  zip.file(
    "README.txt",
    `Static export of "${site.name}" — generated by WebForge.\n\n` +
      `Each .html file is fully self-contained (CSS inlined). Open index.html, or\n` +
      `upload the folder to any static host (Netlify, GitHub Pages, Cloudflare Pages, S3…).\n`,
  );

  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  return { buffer, filename: `${site.slug}.zip` };
}
